### ISSUE TITLE
json version files are completely rewritten

### ISSUE THREAD

**Issue by tomgrv** [gitex-flow/gitex-flow-node#27]
Hi

Thanks for your initiative, looks great.

One issue there: json version files are completely rewritten with { space : 2 }   (option for fs-extra.writeJSON())

=> this breaks formatting rules in place ( prettier config set to { space : 4 } in my case )

**Comment by CuddlySheep** [comment]
Thank you very much for your feedback.
I'll check it out as soon as possible.

**Comment by CuddlySheep** [comment]
I hope the new version 2.0.5 works for you.
The new version uses the following module to preserve the spaces:
[write-pkg](https://github.com/sindresorhus/write-pkg#readme)

I created an unit test for your case:
[unit test](https://github.com/gitex-flow/gitex-flow-node/blob/1c23b66878e6d6b8d34d5485dae11ef8e487b26b/test/GFlow.test.ts#L292)
