### ISSUE TITLE
Error running release finish

### ISSUE THREAD

**Issue by bsimakis** [gitex-flow/gitex-flow-node#80]
Node: 20.9.0
package manager: pnpm
CLI: gitflow-cjs 2.2.1
gitex-flow: 2.4.0
cmd: gitex-flow release finish

Config: 
```json
{
  "projectConfig": {
    "changelog": {
      "type": "ConventionalChangelog"
    },
    "bumpVersionFiles": [
      "package.json"
    ]
  }
}
```

Error: 
```stacktrace
[2024-01-16T03:45:26.455] [INFO] gitex-flow [release] - Finishing release branch "0.3.0"
[2024-01-16T03:45:33.709] [ERROR] gitex-flow - RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at new NodeError (node:internal/errors:406:5)
    at Socket.onChildStdout (node:child_process:490:14)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:345:11)
    at Readable.push (node:internal/streams/readable:286:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'ERR_CHILD_PROCESS_STDIO_MAXBUFFER',
  cmd: 'git flow release finish -m 0.3.0 "0.3.0"'
}
```

**Comment by bsimakis** [comment]
Checking the commits and seems to be while creating the tag as the release branch was merged to master.

**Comment by bsimakis** [comment]
Also didn't merge back to develop.

**Comment by jrebmann** [comment]
Hi @bsimakis,

thank you very much for your report.

It seems that the response of the executed bash command is much larger than expected. Can you please run the raw git flow command (`git flow release finish -m 0.3.0 "0.3.0"`) directly in your console and post the result here?

Which operating system do you use?

**Comment by bsimakis** [comment]
@jrebmann - 

I am running within a Bitbucket Pipeline so it is running in Docker, specifically the node:20.9.0 image. 

1. I have attached the bitbucket-pipelines.yml with the release pipeline using gitflow. I recently updated to use pnpm but had successfully create the release using this pipeline with npm last summer. 
2. I have attached the logs from the pipeline run using the raw git flow command. It was successful but as you can see the output is huge as in a previous run I accidentally committed the pnpm cache. 

NOTE: I have removed the specific repo details but the rest of the logs are present. 

[pipelineLog-{db2f0e6e-ece6-4bed-98a7-ac929e1dbbc2}.txt](https://github.com/gitex-flow/gitex-flow-node/files/13999301/pipelineLog-.db2f0e6e-ece6-4bed-98a7-ac929e1dbbc2.txt)

[bitbucket-pipelines.yml.txt](https://github.com/gitex-flow/gitex-flow-node/files/13999316/bitbucket-pipelines.yml.txt)

**Comment by bsimakis** [comment]
@jrebmann Thank you for providing a way to get around the stashing error and while annoying, it was not the bug I was reporting. 

The log file you are looking at is for when I used the raw gitflow command you suggested, instead of release:finish.  You can see all the output that that command makes (Starts on line 244) which maxes out the buffer and causes the error I reported originally.

**Comment by jrebmann** [comment]
Okey thanks for the hint. After the command `git flow release finish -m 0.3.0 "0.3.0"` there is a lot of console output.

This explains why the string buffer of gitex-flow overflows.

Now the question is why there is so much console output. The `git flow release finish` obviously causes a huge merge with the 'master' branch.

Unfortunately, there is no environment variable to increase the buffer.
According to the documentation, the standard buffer is only 200KB (https://stackoverflow.com/a/23429654), which is too little for such a large log.

The `maxBuffer` option can be set centrally in the following line:

https://github.com/gitex-flow/gitex-flow-node/blob/45f3bca82663fbfe05e1cc5984f37a4e3161450e/src/avh/GitFlowBashExecuter.ts#L79

I will do this for the next bugfix release.

Thank you very much for reporting this issue.
